language: node_js
node_js:
- '0.12'
sudo: required
dist: trusty
before_install:
- sudo apt-get update -qq
- sudo apt-get --assume-yes install libsdl1.2-dev libgif-dev libjson-glib-dev libglib2.0-dev
script:
- make travis-deps
- make release RELOCATE_DEPS=true
addons:
  coverity_scan:
    project:
      name: "jonnor/imgflo"
      description: "Build submitted via Travis CI"
    notification_email: jononor@gmail.com
    build_command_prepend: "make travis-deps"
    build_command: "make RELOCATE_DEPS=true"
    branch_pattern: coverity_scan
  apt:
    packages:
    - libsdl1.2-dev
    - libgif-dev
    - libjson-glib-dev
    - libglib2.0-dev
env:
  global:
  - secure: CEEU3wEYghclP+xxrNOh0SrrHpviu9eDfVTOAlez4YLKKy4MTriB4+MyTPdWV6nvGji3hh4bFAAfEw8aaQtNKSDYxpcqoUVaMhnqITzhd/6J+zuRTXNZqsk13ybtTE+gfvdVIOREcEyeh2n7gXut+T2lC+p8H4ZDvHM8VKx3I4Q=
  - secure: Hc++pZNwr3i3YL0jqVzubrtcYm8cztXh7Bg9XOO2lg68Gn6GFvM8tojeM1BrHQsvfu40ps2IGFsPLVXlOSQd2KNjpMq/aJpxBvA0+15sB1n0NivarrnUurJ5YNtRnIh9Yte/Oe29XlAp5Zyeklqw+4BJEHVA8FgoIwHQ9A8UOUs=
  - secure: bn2LKPSiutww2z6+GDh2KYUDwW3Sj/SA16EWxoxiDPeIssWR71naxh0rIbs9gM2zcgrBQaVbVh4a4b/LkUywZhQiAFl1c+axK6pra4A9wOQbq8vZXK37TJXGTDs5rCu08Z3cB/uuqrky/Ju4XMxGRGwwECs3SZJ4NhDpDdne4iU=
